# Generated by Django 5.0.4 on 2024-05-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OceanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Unknown', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('depth', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('salinity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
